

#ifdef __cplusplus
extern "C" {
#endif

#define NFL_START_BOOTSTRAP  (0x0300)

#define NFL_START_DISCOVERY    (0x0301)

#define NFL_START_ACCESS_CONSUMER  (0x0308)

#define NFL_START_ACCESS_PRODUCER  (0x030A)

#define NFL_START_DISCOVERY_QUERY    (0x0305)

#define NFL_START_DISCOVERY_QUERY_REPLY    (0x0307)

#define NFL_EXTRACT_BOOTSTRAP_TUPLE    (0x0302)

#define NFL_EXTRACT_DISCOVERY_LIST   (0x0303)

#define NFL_SET_DISCOVERY_PREFIX  (0x0306)

#define NFL_INIT_DISCOVERY  (0x0309)

#define NFL_INIT_ACCESS  (0x030B)

#ifdef __cplusplus
}
#endif

